# config/routes.yaml

app_front:
    path: /
    controller: App\Controller\FrontController::index

app_front_actualites:
    path: /actualites
    controller: App\Controller\FrontController::actu

app_front_contact:
    path: /contact
    controller: App\Controller\FrontController::contact

admin_dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

app_login:
    path: /login
    controller: App\Controller\SecurityController::login


